version: 2
updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"

    # Maintain dependencies for Python packages
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
          
    # Maintain dependencies for Git submodules
    - package-ecosystem: "gitsubmodule"
      directory: "/"
      schedule:
          interval: "weekly"
