#!/bin/sh

talondoc autogen \
		--output-dir example/docs/knausj_talon \
		--sphinx-root example/docs \
		--project 'knausj_talon' \
		--package-name user \
		--no-generate-conf \
		--exclude 'conftest.py' \
		--exclude 'test/**' \
		--exclude '**/*.py' \
		example/knausj_talon/

sphinx-build -M "clean" "example/docs" "example/docs/_build"

sphinx-build -M "html" "example/docs" "example/docs/_build"
